[package]
name = "ogn-ws-gateway"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]

[dependencies]
rand = "*"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
regex = "1.0.0"
lazy_static = "1.0.0"

actix = "0.5"
actix-web = "^0.6"
