[package]
name = "ogn-web-gateway"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"

failure = "0.1"

actix = "0.7.7"
actix-web = { version = "0.7.19", features = ["default", "alpn"] }
actix-ogn = "0.2"
futures = "0.1"

chrono = "0.4.7"
regex = "1"
lazy_static = "1.3.0"
itertools = "0.8"

sentry = "0.15.2"

serde = "1.0.93"
serde_derive = "1.0.94"
serde_json = "1.0"
bincode = "1.1.4"

r2d2_redis = "0.9"

systemstat = "0.1.4"
clap = "2.33.0"

[dev-dependencies]
approx = "0.3.2"
