[package]
name = "ogn-web-gateway"
version = "0.1.0"
authors = ["Tobias Bieniek <tobias.bieniek@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"

failure = "0.1"

actix = "0.8.3"
actix-cors = "0.1.0"
actix-files = "0.1.4"
actix-web = { version = "1.0.7", features = ["client", "ssl"] }
actix-web-actors = "1.0.2"
actix-ogn = "0.3"
futures = "0.1"

chrono = "0.4.9"
regex = "1"
lazy_static = "1.4.0"
itertools = "0.8"

sentry = "0.17.0"

serde = "1.0.100"
serde_derive = "1.0.100"
serde_json = "1.0"
bincode = "1.1.4"

r2d2_redis = "0.9"

systemstat = "0.1.4"
clap = "2.33.0"

[dev-dependencies]
approx = "0.3.2"
